# Generated by Django 2.0.8 on 2018-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0003_auto_20180919_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpvalidation',
            name='type',
        ),
        migrations.AddField(
            model_name='otpvalidation',
            name='prop',
            field=models.CharField(choices=[('E', 'EMail Address'), ('M', 'Mobile Number')], default='E', max_length=3, verbose_name='Destination Property'),
        ),
    ]
