# Generated by Django 2.1.3 on 2018-11-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0004_auto_20181015_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtransaction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='authtransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='authtransaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date/Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtransaction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtransaction',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='reactive_at',
            field=models.DateTimeField(verbose_name='ReActivate Sending OTP'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
