# Generated by Django 2.1.4 on 2018-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0005_auto_20181123_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='otp',
            field=models.CharField(max_length=10, verbose_name='OTP Code'),
        ),
    ]
