# Generated by Django 3.1.2 on 2020-10-02 02:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_user", "0006_auto_20181220_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Profile Photo"
            ),
        ),
    ]
