# Generated by Django 3.1.2 on 2021-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0007_auto_20201031_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='authtransaction',
            name='refresh_token',
            field=models.TextField(blank=True, verbose_name='JWT Refresh Token'),
        ),
        migrations.AlterField(
            model_name='authtransaction',
            name='token',
            field=models.TextField(verbose_name='JWT Access Token'),
        ),
    ]
