exclude: .+/migrations/.+\.py
repos:
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          args: [--max-line-length=88]

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
        - id: reorder-python-imports

    - repo: https://github.com/econchick/interrogate
      rev: 1.5.0
      hooks:
        - id: interrogate
          args: [--fail-under=100, -v]
          exclude: ^(docs/conf.py|setup.py)

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-yaml
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: debug-statements
        - id: requirements-txt-fixer
