# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true

exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

labels: []

ignore_labels:
  - restyled-ignore

restylers_version: "20200825"

restylers:
  - autopep8:
      enabled: false
  - isort:
      enabled: false
  - yapf:
      enabled: false
  - "*"
