# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_custom_modules.db_type


class Migration(migrations.Migration):

    dependencies = [
        ('userprofileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpvalidation',
            name='reactive_at',
            field=django_custom_modules.db_type.UnixTimestampField(default=datetime.datetime(2017, 10, 15, 21, 12, 25, 966287)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpvalidation',
            name='sms_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='SMS ID'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile Number'), ('email', 'EMail Address')], default='email', max_length=15, verbose_name='EMail/Mobile'),
        ),
    ]
